name: flutter_address_from_latlng
description: A Dart package to get addresses from latitude and longitude.Provide vast number of method to get verious types of location by latitude and longitude.
version: 0.0.3
homepage: 'https://github.com/saiful00000/flutter_address_from_latlng'

environment:
  sdk: ">=3.0.0"
  flutter: ">=1.17.0"

dependencies:
  # http: ^0.13.4
  http: ^1.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter: